using Microsoft.EntityFrameworkCore;
using CrmArrighi.Data;

public static class CreateTableHelper
{
    public static async Task CreateParceirosTableIfNotExists(CrmArrighiContext context)
    {
        try
        {
            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""Parceiros"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PessoaFisicaId"" integer NOT NULL,
                    ""FilialId"" integer NOT NULL,
                    ""OAB"" character varying(20) NULL,
                    ""Email"" character varying(100) NULL,
                    ""Telefone"" character varying(20) NULL,
                    ""DataCadastro"" timestamp without time zone NOT NULL,
                    ""DataAtualizacao"" timestamp without time zone NULL,
                    ""Ativo"" boolean NOT NULL,
                    CONSTRAINT ""PK_Parceiros"" PRIMARY KEY (""Id"")
                );

                ALTER TABLE ""Parceiros""
                    ADD COLUMN IF NOT EXISTS ""Email"" character varying(100) NULL;

                ALTER TABLE ""Parceiros""
                    ADD COLUMN IF NOT EXISTS ""Telefone"" character varying(20) NULL;

                CREATE INDEX IF NOT EXISTS ""IX_Parceiros_FilialId""
                    ON ""Parceiros"" (""FilialId"");

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Parceiros_PessoaFisicaId""
                    ON ""Parceiros"" (""PessoaFisicaId"");

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_Parceiros_Filiais_FilialId'
                    ) AND to_regclass('""Filiais""') IS NOT NULL THEN
                        ALTER TABLE ""Parceiros""
                            ADD CONSTRAINT ""FK_Parceiros_Filiais_FilialId""
                            FOREIGN KEY (""FilialId"") REFERENCES ""Filiais"" (""Id"")
                            ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_Parceiros_PessoasFisicas_PessoaFisicaId'
                    ) AND to_regclass('""PessoasFisicas""') IS NOT NULL THEN
                        ALTER TABLE ""Parceiros""
                            ADD CONSTRAINT ""FK_Parceiros_PessoasFisicas_PessoaFisicaId""
                            FOREIGN KEY (""PessoaFisicaId"") REFERENCES ""PessoasFisicas"" (""Id"")
                            ON DELETE RESTRICT;
                    END IF;
                END $$;
            ");

            Console.WriteLine("Tabela Parceiros verificada/criada com sucesso.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Erro ao criar tabela Parceiros: {ex.Message}");
        }
    }
}
